tools:
    php_sim: true
    php_pdepend: true
    php_analyzer: true
    external_code_coverage:
        timeout: 600
filter:
    excluded_paths:
        - 'spec/*'
        - 'tests/*'
        - 'Manager/*'