language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - hhvm

branches:
  only:
    - master
    - dev

before_script:
  - curl -s https://getcomposer.org/installer | php
  - $(which php) composer.phar --dev --no-progress --no-interaction install

script:
  - bin/phpunit --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --access-token="e4c700772ac67a0210fa0054a54c34bfb5eac71883df0bd2d23ccb03e264be14" --format=php-clover coverage.clover
  
