language: php

php:
  - 7.2.0

branches:
  only:
    - master
    - dev

before_script:
  - curl -s https://getcomposer.org/installer | php
  - $(which php) composer.phar --dev --no-progress --no-interaction install

script:
  - bin/phpunit
  - bin/phpunit --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
