language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

branches:
  only:
    - master
    - dev

before_script:
  - curl -s https://getcomposer.org/installer | php
  - $(which php) composer.phar --dev --no-progress --no-interaction install

script:
  - bin/phpunit
